import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./global.css";

import { AppProvider } from "@/providers/AppProvider";
import { MainLayout } from "@/components/layout/MainLayout";

const inter = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <MainLayout>{children}</MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
